### ISSUE TITLE
need help for standard layout

### ISSUE THREAD

**Issue by ekm507** [sadeg/turkcekeyboard#1]
Hi,
I found this repo from [Wikipedia](https://azb.wikipedia.org/wiki/%D9%88%DB%8C%DA%A9%DB%8C%E2%80%8C%D9%BE%D8%AF%DB%8C%D8%A7:%D8%AA%DB%86%D8%B1%DA%A9%D8%AC%D9%87_%DA%A9%DB%8C%D8%A8%D9%88%D8%B1%D8%AF).

I noticed the difference between your keyboard layout and the layout on wiki page. I am wondering if there is any standard.

your keyboard:
![turkcekeyboard layout](https://github.com/sdqri/turkcekeyboard/assets/13185969/69d7d404-d7ca-4d7c-9e46-7eead979fec8)

the keyboard in Wikipedia page:
![keyboard in wikipedia](https://github.com/sdqri/turkcekeyboard/assets/13185969/411dd2b5-4a98-4bbf-bc2f-681a4142e4ea)

also there is this layout in Gboard (Google keyboard app for android)
![image](https://github.com/sdqri/turkcekeyboard/assets/13185969/9af521e2-83b5-4923-8e4b-27a63dc642d0)

I am looking for an Azerbaijani keyboard layout for GNU/Linux. is there any? if not, I am willing to make one. can you provide me some reference for standard layout?

any other help is appreciated.
thank you.

**Comment by sdqri** [comment]
Thanks for reaching out and I appreciate your interest in creating an Azerbaijani keyboard layout for GNU/Linux. Your initiative is respected, and I'm here to help in any way I can.
Regarding your question about standard layouts, When creating the keyboard layout for Azerbaijani, I referenced the results of the Turkish orthography seminar held in Tehran in October 2001. These results provided valuable insights for orthographic decisions, and you can access them [here](http://www.azeri.org/Azeri/az_arabic/arabic_index.html). Azerbaijani, with its south and north variants, is mutually intelligible and lexically similar. ISO 639-3 classifies them as a [macrolanguage](https://iso639-3.sil.org/code/aze) with two members. Due to the absence of established standards in this domain at the time the AZB Wikipedia was in incubator, we sought tools to make typing easier. This led to the decision to either create a new layout or adapt an existing one for development.
I believe the keyboard layout depicted on the wiki page is a variation of the [Persian standard keyboard](https://learn.microsoft.com/en-us/globalization/keyboards/kbdfar). It uses non-existent letters in place of accents and diacritical marks, needing a shift press for typing. This layout was initially present when I was developing this one. Both I and some of my friends, specifically those familiar with the north variant of the language, found that layout impractical. This was due to its use of two keys for some common letters in the language.
So we created a layout based on the [Azerbaijani Latin Keyboard](https://learn.microsoft.com/en-us/globalization/keyboards/kbdazel) with minimal modifications to the layout itself to make it more usable for us. Though later the [Azerbaijani Standard Keyboard](https://learn.microsoft.com/en-us/globalization/keyboards/kbdazst) was introduced which is different. As for the layout in Gboard, I am not familiar with its development strategy.

**Comment by ekm507** [comment]
thanks so much for your great help. :heart:
